[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.30.0", features = ["hashes", "rand", "std"] }
serde = { version = "1.0.217", features = ["derive"] }
